version: '3.8'

services:
  db:
    image: postgres:15
    container_name: office_app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: office_app
      TZ: Asia/Kolkata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Office-management-railway-deployment/db/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
